services:
  {{ cookiecutter.project_name }}:
    container_name: {{ cookiecutter.project_name }}
    network_mode: host
    init: true
    build:
      context: .
      dockerfile: dockerfiles/{{ cookiecutter.project_name }}/Dockerfile
    ports:
      - 9000:9000
    environment:
      - environment=integration
    healthcheck:
         test: curl -f http://localhost:9000/health || exit 1
         interval: 10s
         timeout: 5s
         retries: 3
  test-runner:
    network_mode: host
    build:
      context: .
      dockerfile: dockerfiles/test/Dockerfile
    depends_on:
      - {{ cookiecutter.project_name }}
    environment:
      - api_address=http://localhost:9000
