version: "3.1"
services:
  {{ cookiecutter.project_name }}:
    container_name: {{ cookiecutter.project_name }}
    network_mode: host
    init: true
    build:
      context: .
      dockerfile: dockerfiles/{{ cookiecutter.project_name }}/Dockerfile
    ports:
      - 9000:9000
  test-runner:
    network_mode: host
    build:
      context: .
      dockerfile: dockerfiles/test/Dockerfile
    depends_on:
      - {{ cookiecutter.project_name }}
    command:
      [
        "./bin/wait-for-it.sh",
        "localhost:9000",
        "--",
        "make",
        "integration",
      ]
    environment:
      - API_ADDRESS=http://localhost:9000
